serverUrl: localhost:8000
sshUrl: localhost:2222
tunnelUrl: localhost:8001
secretKey: 57b4L4I4XcU-Wcu548rnqaahGbyykszmdD72y-dVI9
useLocalhost: true
debug: true
tunnels:
  - name: portr
    subdomain: portr
    port: 4321
    type: tcp
